[theme]
primaryColor = "#007BFF"      # Blue
backgroundColor = "#FFFFFF"   # White
secondaryBackgroundColor = "#F0F2F6"  # Light grayish white for a subtle contrast
textColor = "#000000"         # Black text for readability
font = "sans serif"           # Professional sans-serif font


